SELECT "Inserción de Usuarios";
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Juan Gómez Díaz","juan@mail.com",1234567890,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"José Luis Sánchez Martínez","joseluis@mail.com",1234567891,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"José Rodríguez Pérez","jose@mail.com",1234567892,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"María Guadalupe Gómez García","maria@mail.com",1234567893,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Francisco Fernández Sánchez","francisco@mail.com",1234567894,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Lizbeth Castillo Romero","guadalupe@mail.com",1234567895,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"María Sánchez Díaz","maria@mail.com",1234567896,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Juana López Ortiz","juana@mail.com",1234567897,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Antonio Díaz Ávila","antonio@mail.com",1234567898,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Jesús Martínez Hernández","jesus@mail.com",1234567899,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Miguel Alejandro Castillo Mendoza","miguelangel@mail.com",1234567900,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Pedro García Soto","pedro@mail.com",1234567901,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Alejandro Sánchez Campos","alejandro@mail.com",1234567902,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Manuel Alejandro Romero Suárez","manuel@mail.com",1234567903,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Margarita Sánchez Morales","margarita@mail.com",1234567904,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"María Del Carmen Romero Castillo","mariadelcarmen@mail.com",1234567905,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Juan Carlos Sánchez Ortiz","juancarlos@mail.com",1234567906,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Roberto González Ávila","roberto@mail.com",1234567907,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Fernando González Hernández","fernando@mail.com",1234567908,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Daniel Sosa Mendoza","daniel@mail.com",1234567909,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Carlos Torres Soto","carlos@mail.com",1234567910,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Jorge Álvarez Campos","jorge@mail.com",1234567911,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Ricardo Fernández Chávez","ricardo@mail.com",1234567912,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Emmanuel de Jesús Suárez Gómez","miguel@mail.com",1234567913,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (0,"Eduardo Morales López","eduardo@mail.com",1234567914,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (1,"Javier Pérez Díaz","javier@mail.com",1234567915,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (1,"Arturo Castillo López","arturo@mail.com",1234567916,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (1,"Marco Antonio Sánchez Díaz","marcoantonio@mail.com",1234567917,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (1,"José Manuel López Martínez","josemanuel@mail.com",1234567918,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (1,"Francisco Javier Díaz Morales","franciscojavier@mail.com",1234567919,"a1b2c3d4",NULL);
INSERT INTO Usuarios(Perfil,Nombre,Email,Celular,Password, FotoPerfil) VALUES (1,"Admin Admin","admin@admin.com",1234567919,"adminadmin",NULL);

SELECT "Inserción de Habilidades";
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (1,"Matemáticas","Trigonometría",80,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (1,"Física","Electromagnetismo",90,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (2,"Química","Química orgánica",95,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (2,"Español","Literatura moderna",80,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (3,"Informática","Redes",89,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (3,"Idiomas","Inglés",95,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (4,"Finanzas","Balance general",100,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (4,"Ciencias Naturales","Evolución",98,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (5,"Química","Química orgánica",96,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (5,"Matemáticas","Cálculo",90,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (6,"Física","Electromagnetismo",92,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (6,"Química","Química inorgánica",93,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (7,"Español","Literatura romance",94,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (7,"Informática","Algoritmos",89,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (8,"Idiomas","Alemán",88,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (8,"Finanzas","Balance general",99,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (9,"Idiomas","Francés",96,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (9,"Matemáticas","Álgebra lineal",90,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (10,"Física","Cargas eléctricas",100,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (10,"Finanzas","Estados financieros",100,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (11,"Español","Literatura moderna",88,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (11,"Informática","Circuitos",86,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (12,"Idiomas","Alemán",85,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (12,"Finanzas","Balance general",86,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (13,"Ciencias sociales","Ética",86,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (13,"Matemáticas","Trigonometría",95,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (14,"Física","Cargas eléctricas",97,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (14,"Química","Química inorgánica",97,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (15,"Español","Literatura romance",99,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (15,"Informática","Algoritmos",96,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (16,"Idiomas","Inglés",91,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (16,"Finanzas","Estados financieros",93,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (17,"Ciencias sociales","Ética",90,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (17,"Matemáticas","Estadística",82,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (18,"Física","Leyes de Newton",83,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (18,"Química","Compuestos químicos",93,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (19,"Español","Literatura moderna",96,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (19,"Informática","Circuitos",83,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (20,"Idiomas","Francés",98,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (20,"Finanzas","Derecho financiero",82,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (21,"Ciencias Sociales","Derecho mercantil",96,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (21,"Matemáticas","Álgebra lineal",99,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (22,"Física","Termodinámica",100,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (22,"Química","Compuestos químicos",100,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (23,"Español","Literatura romance",92,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (23,"Informática","Seguridad informática",88,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (24,"Idiomas","Francés",76,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (24,"Finanzas","Análisis financiero",96,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (25,"Ciencias Sociales","Derecho financiero",88,NULL);
INSERT INTO Habilidades(IDUsuario, Materia, Habilidad, ValoracionPromedio, PremioActual) VALUES (25,"Idiomas","Alemán",95,NULL);

SELECT "Insercion FormaPago";
INSERT INTO FormaPago(FormaPago, FechaAlta, IDUsuarioAlta) VALUES ("Efectivo",CURDATE(),31);
INSERT INTO FormaPago(FormaPago, FechaAlta, IDUsuarioAlta) VALUES ("Transferencia bancaria",CURDATE(),31);
INSERT INTO FormaPago(FormaPago, FechaAlta, IDUsuarioAlta) VALUES ("Depósito Oxxo",CURDATE(),31);
INSERT INTO FormaPago(FormaPago, FechaAlta, IDUsuarioAlta) VALUES ("Tarjeta de prepago",CURDATE(),31);
INSERT INTO FormaPago(FormaPago, FechaAlta, IDUsuarioAlta) VALUES ("Bono gratis",CURDATE(),31);

SELECT "Insercion FormaPagoUsuario";
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (1,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (1,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (2,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (2,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (3,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (3,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (4,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (4,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (5,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (5,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (6,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (6,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (7,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (7,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (8,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (8,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (9,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (9,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (10,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (10,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (11,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (11,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (12,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (12,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (13,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (14,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (15,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (16,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (17,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (18,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (19,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (20,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (21,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (22,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (23,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (24,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (25,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (26,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (26,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (26,3,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (27,4,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (27,5,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (27,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (27,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (28,3,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (28,4,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (29,5,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (30,1,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (30,2,CURDATE());
INSERT INTO FormaPagoUsuario(IDUsuario, IDFormaPago, FechaAlta) VALUES (30,3,CURDATE());

SELECT "Inserción Direccion";
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (1,"Gardenias","35","","94470","Villas Atlixco","San Andrés Cholula","Cholula","Puebla");
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (2,"Mariscos","55","1","92197","Villas Marinas","San Andrés Cholula","Cholula","Puebla");
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (3,"Villa del Sol","2B","","72197","Villas Solares","San Andrés Cholula","Cholula","Puebla");
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (4,"Villa de los Ahuehuetes","4C","2","35500","Villas del Bosque","Puebla","Puebla","Puebla");
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (5,"Oriente 2","456","","92471","Centro","Puebla","Puebla","Puebla");
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (6,"Carranza","2","","91201","Héroes","Puebla","Puebla","Puebla");
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (7,"Huatusco","409","2","94472","Centro","Puebla","Puebla","Puebla");
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (8,"Maravillas","","","72196","Centro","Puebla","Puebla","Puebla");
INSERT INTO Direccion(IDUsuario, Calle, NumExterior, NumInterior, CP, Colonia, Municipio, Ciudad, Estado) VALUES (9,"Andrómeda","112B","","92197","Galaxia","San Andrés Cholula","Cholula","Puebla");

